# Generated by Django 5.0.6 on 2026-08-30 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=150)),
                ('institution', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='Crystal Delta', max_length=150)),
                ('designation', models.CharField(default='Software Developer', help_text='Official designation. Edit here once confirmed.', max_length=150)),
                ('location', models.CharField(default='Aruppukottai, Tamil Nadu', max_length=150)),
                ('start_date', models.CharField(blank=True, help_text='e.g. 2023 (leave blank if unknown)', max_length=50)),
                ('end_date', models.CharField(blank=True, default='Present', max_length=50)),
                ('is_current', models.BooleanField(default=True)),
                ('responsibilities', models.TextField(default='Developing modern web applications\nBuilding reusable React components\nDeveloping REST APIs\nWorking with Node.js and Express.js\nMongoDB database integration\nFrontend and backend integration\nAuthentication and authorization\nAPI testing and debugging\nResponsive UI development\nDatabase management', help_text='One responsibility per line.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='P. Sivakumar', max_length=150)),
                ('title_primary', models.CharField(default='MERN Stack Developer', max_length=150)),
                ('title_secondary', models.CharField(default='Full Stack Developer', max_length=150)),
                ('tagline', models.TextField(default='Building modern, scalable and user-focused web applications using the MERN stack, React and modern backend technologies.')),
                ('about_text', models.TextField(default='Passionate MERN Stack Developer with 2+ years of experience turning ideas and business requirements into responsive, scalable web applications. Experienced in React.js, Node.js, Express.js, and MongoDB, with a strong focus on clean code, API development, performance, and user experience. Brings a practical problem-solving mindset and the ability to work effectively across the full development lifecycle.')),
                ('current_company', models.CharField(default='Crystal Delta', max_length=150)),
                ('location', models.CharField(default='Aruppukottai, Tamil Nadu, India', max_length=150)),
                ('email', models.EmailField(default='sivap4817@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+91 8489291309', max_length=20)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField(blank=True)),
                ('role_responsibilities', models.TextField(blank=True, help_text='One item per line. Leave blank if not verified.')),
                ('features', models.TextField(blank=True, help_text='One feature per line.')),
                ('live_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('twitter', 'Twitter / X'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='portfolio.project')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_primary_stack', models.BooleanField(default=False, help_text='Check for MERN core skills (React, Node, Express, MongoDB) to make them visually prominent.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.skillcategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
